import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ORG = 'AtyaLibraries'
const API = 'https://api.github.com'
const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN

const headers = {
  Accept: 'application/vnd.github+json',
  'X-GitHub-Api-Version': '2022-11-28',
}

if (token) {
  headers.Authorization = `Bearer ${token}`
}

async function getJson(url) {
  const response = await fetch(url, { headers })

  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${response.status} ${response.statusText}`)
  }

  return response.json()
}

async function getAllPages(url) {
  const items = []
  let next = url

  while (next) {
    const response = await fetch(next, { headers })

    if (!response.ok) {
      throw new Error(`GET ${next} failed: ${response.status} ${response.statusText}`)
    }

    items.push(...await response.json())
    const link = response.headers.get('link') || ''
    const match = link.match(/<([^>]+)>;\s*rel="next"/)
    next = match ? match[1] : ''
  }

  return items
}

function propertyValue(properties, name) {
  const property = properties.find((item) => item.property_name === name)
  const value = property?.value
  return Array.isArray(value) ? value[0] : value
}

async function getPackageId(repo, branch) {
  // Template repos ship a `dotnet new` template with multiple projects under src/,
  // so there is no single canonical package project to scan. Their published package
  // id equals the repo name (e.g. Atya.Templates.UiAutomation).
  if (/^Atya\.Templates\./u.test(repo)) {
    return repo
  }

  const tree = await getJson(`${API}/repos/${ORG}/${repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`)
  const projects = tree.tree
    .filter((item) => item.type === 'blob')
    .map((item) => item.path)
    .filter((item) => /^src\/.+\.csproj$/u.test(item))

  const canonicalProject = `src/${repo}/${repo}.csproj`
  const packageProjects = projects.includes(canonicalProject) ? [canonicalProject] : projects

  if (packageProjects.length !== 1) {
    throw new Error(`${repo}: expected exactly one package project under src, found ${projects.length}`)
  }

  const content = await getJson(`${API}/repos/${ORG}/${repo}/contents/${encodeURIComponent(packageProjects[0])}?ref=${encodeURIComponent(branch)}`)
  const projectXml = Buffer.from(content.content, 'base64').toString('utf8')
  const match = projectXml.match(/<PackageId>([^<]+)<\/PackageId>/u)

  if (!match) {
    throw new Error(`${repo}: PackageId not found in ${projects[0]}`)
  }

  return match[1]
}

function inferCategory(packageId) {
  const parts = packageId.split('.')
  return parts.length >= 3 ? parts[1] : 'Tooling'
}

function inferType(packageId) {
  return packageId.includes('.Templates.') ? 'template' : 'library'
}

function renderData({ categories, packages }) {
  return `// Generated by scripts/generate-data.mjs. Edit src/data.overrides.json for descriptions and categories.

export const ORG = 'AtyaLibraries'
export const NUGET_PROFILE = 'https://www.nuget.org/profiles/ArsenAsulyan'
export const GITHUB_ORG = 'https://github.com/AtyaLibraries'

export const CATEGORIES = ${JSON.stringify(categories, null, 2)}

export const PACKAGES = ${JSON.stringify(packages, null, 2)}

export function installCommand(pkg) {
  if (pkg.type === 'template') return \`dotnet new install \${pkg.id}\`
  if (pkg.type === 'sdk') return \`// global.json\\n"msbuild-sdks": { "\${pkg.id}": "*" }\`
  return \`dotnet add package \${pkg.id}\`
}

export function nugetUrl(pkg) {
  return \`https://www.nuget.org/packages/\${pkg.id}\`
}

export function githubUrl(pkg) {
  return \`https://github.com/\${ORG}/\${pkg.repo}\`
}
`
}

const overrides = JSON.parse(await readFile('src/data.overrides.json', 'utf8'))
const repos = await getAllPages(`${API}/orgs/${ORG}/repos?per_page=100&type=public`)
const packages = []

for (const repo of repos.sort((left, right) => left.name.localeCompare(right.name))) {
  const properties = await getJson(`${API}/repos/${ORG}/${repo.name}/properties/values`)

  if (propertyValue(properties, 'atya-managed') !== 'true') {
    continue
  }

  const id = await getPackageId(repo.name, repo.default_branch)
  const override = overrides.packages[id] || {}

  packages.push({
    id,
    repo: repo.name,
    category: override.category || inferCategory(id),
    type: override.type || inferType(id),
    description: override.description || repo.description || `${id} package.`,
  })
}

packages.sort((left, right) => left.category.localeCompare(right.category) || left.id.localeCompare(right.id))

await mkdir(path.dirname('src/data.js'), { recursive: true })
await writeFile('src/data.js', renderData({ categories: overrides.categories, packages }), 'utf8')
console.log(`Generated src/data.js with ${packages.length} packages.`)
