// Generated by scripts/generate-data.mjs. Edit src/data.overrides.json for descriptions and categories.

export const ORG = 'AtyaLibraries'
export const NUGET_PROFILE = 'https://www.nuget.org/profiles/ArsenAsulyan'
export const GITHUB_ORG = 'https://github.com/AtyaLibraries'

export const CATEGORIES = [
  {
    "key": "all",
    "label": "All"
  },
  {
    "key": "Foundation",
    "label": "Foundation"
  },
  {
    "key": "Diagnostics",
    "label": "Diagnostics"
  },
  {
    "key": "Errors",
    "label": "Errors"
  },
  {
    "key": "Web",
    "label": "Web"
  },
  {
    "key": "Application",
    "label": "Application"
  },
  {
    "key": "Governance",
    "label": "Governance"
  },
  {
    "key": "Tooling",
    "label": "Tooling"
  }
]

export const PACKAGES = [
  {
    "id": "Atya.Application.Mediator",
    "repo": "Mediator",
    "category": "Application",
    "type": "library",
    "description": "Source-generated, reflection-free mediator contracts and dispatch for Result-returning handlers."
  },
  {
    "id": "Atya.Diagnostics.Logging",
    "repo": "Logging",
    "category": "Diagnostics",
    "type": "library",
    "description": "Logging abstractions and dependency-injection helpers for Atya diagnostics."
  },
  {
    "id": "Atya.Diagnostics.Metrics",
    "repo": "Metrics",
    "category": "Diagnostics",
    "type": "library",
    "description": "Metrics abstractions and dependency-injection helpers for Atya diagnostics."
  },
  {
    "id": "Atya.Diagnostics.Observation",
    "repo": "Observation",
    "category": "Diagnostics",
    "type": "library",
    "description": "Unified observation helpers that compose logging, metrics, and tracing."
  },
  {
    "id": "Atya.Diagnostics.OpenTelemetry",
    "repo": "OpenTelemetry",
    "category": "Diagnostics",
    "type": "library",
    "description": "OpenTelemetry configuration and instrumentation helpers for .NET services."
  },
  {
    "id": "Atya.Diagnostics.Tracing",
    "repo": "Tracing",
    "category": "Diagnostics",
    "type": "library",
    "description": "Tracing abstractions and dependency-injection helpers for Atya diagnostics."
  },
  {
    "id": "Atya.Errors.Exceptions",
    "repo": "Exceptions",
    "category": "Errors",
    "type": "library",
    "description": "Exception types and helpers for consistent error handling."
  },
  {
    "id": "Atya.Errors.ProblemDetails",
    "repo": "ProblemDetails",
    "category": "Errors",
    "type": "library",
    "description": "RFC 7807 Problem Details helpers for ASP.NET Core services."
  },
  {
    "id": "Atya.Errors.Validation",
    "repo": "Validation",
    "category": "Errors",
    "type": "library",
    "description": "Validation primitives and error helpers for the Atya error layer."
  },
  {
    "id": "Atya.Foundation.Abstractions",
    "repo": "Abstractions",
    "category": "Foundation",
    "type": "library",
    "description": "Common abstractions shared across the Atya foundation packages."
  },
  {
    "id": "Atya.Foundation.Guards",
    "repo": "Guards",
    "category": "Foundation",
    "type": "library",
    "description": "Lightweight, allocation-friendly guard clauses for argument validation."
  },
  {
    "id": "Atya.Foundation.Primitives",
    "repo": "Primitives",
    "category": "Foundation",
    "type": "library",
    "description": "Primitive types and value objects for the Atya foundation layer."
  },
  {
    "id": "Atya.Foundation.Results",
    "repo": "Results",
    "category": "Foundation",
    "type": "library",
    "description": "Result and Error primitives for expected, recoverable outcomes in Atya libraries."
  },
  {
    "id": "Atya.Foundation.Serialization",
    "repo": "Serialization",
    "category": "Foundation",
    "type": "library",
    "description": "Serialization abstractions and helpers for the Atya foundation layer."
  },
  {
    "id": "Atya.Foundation.Time",
    "repo": "Time",
    "category": "Foundation",
    "type": "library",
    "description": "Time and clock abstractions for testable, deterministic time handling."
  },
  {
    "id": "Atya.Governance.CodeQuality",
    "repo": "CodeQuality",
    "category": "Governance",
    "type": "library",
    "description": "Centralized StyleCop and .NET analyzer configuration for Atya repositories."
  },
  {
    "id": "Atya.Governance.Testing",
    "repo": "Testing",
    "category": "Governance",
    "type": "library",
    "description": "Small, focused test-only helpers for Atya packages and applications."
  },
  {
    "id": "Atya.Templates.NuGetPackage",
    "repo": "Atya.Templates.NuGetPackage",
    "category": "Tooling",
    "type": "template",
    "description": "Production-ready .NET 10 NuGet package starter template."
  },
  {
    "id": "Atya.Web.Middleware",
    "repo": "Middleware",
    "category": "Web",
    "type": "library",
    "description": "ASP.NET Core middleware for exception and Result mapping, ProblemDetails, and correlation IDs."
  }
]

export function installCommand(pkg) {
  if (pkg.type === 'template') return `dotnet new install ${pkg.id}`
  if (pkg.type === 'sdk') return `// global.json\n"msbuild-sdks": { "${pkg.id}": "*" }`
  return `dotnet add package ${pkg.id}`
}

export function nugetUrl(pkg) {
  return `https://www.nuget.org/packages/${pkg.id}`
}

export function githubUrl(pkg) {
  return `https://github.com/${ORG}/${pkg.repo}`
}
